export const STATES = ["New Jersey", "Pennsylvania", "Ohio", "New York", "Delaware", "Maryland"];

export const NICHES_BY_GROUP = {
  "Cleaning Services": [
    "House cleaning",
    "Deep cleaning",
    "Move-in/move-out cleaning",
    "Carpet cleaning",
    "Window cleaning",
    "Pressure washing",
    "Gutter cleaning",
    "Chimney cleaning",
    "Dryer vent cleaning",
    "Air duct cleaning",
    "Pool cleaning",
    "Garage cleaning",
    "Hoarding cleanup",
    "Crime scene cleanup",
    "Biohazard cleanup"
  ],
  "Repair & Maintenance": [
    "Plumber",
    "Electrician",
    "HVAC technician",
    "Appliance repair",
    "Refrigerator repair",
    "Washer/dryer repair",
    "Dishwasher repair",
    "Garage door repair",
    "Lock repair",
    "Window repair",
    "Screen door repair",
    "Fence repair",
    "Deck repair",
    "Roof repair",
    "Gutter repair",
    "Siding repair",
    "Foundation repair",
    "Crawl space repair",
    "Attic repair"
  ],
  "Installation Services": [
    "Ceiling fan installation",
    "Light fixture installation",
    "Smart home installation",
    "Security camera installation",
    "Alarm system installation",
    "TV mounting",
    "Shelf installation",
    "Flooring installation",
    "Tile installation",
    "Hardwood flooring",
    "Carpet installation",
    "Cabinet installation",
    "Countertop installation",
    "Bathroom vanity installation",
    "Water heater installation",
    "Solar panel installation",
    "Generator installation",
    "EV charger installation",
    "Insulation installation"
  ],
  "Landscaping & Outdoor": [
    "Lawn mowing",
    "Lawn care",
    "Tree trimming",
    "Tree removal",
    "Stump removal",
    "Hedge trimming",
    "Leaf removal",
    "Snow removal",
    "Ice dam removal",
    "Sprinkler installation",
    "Irrigation repair",
    "Landscape design",
    "Mulching",
    "Sod installation",
    "Garden maintenance",
    "Flower bed care",
    "Outdoor lighting installation",
    "Patio installation",
    "Deck building",
    "Fence installation",
    "Driveway sealing"
  ],
  "Painting & Finishing": [
    "Interior painting",
    "Exterior painting",
    "Cabinet painting",
    "Deck staining",
    "Fence staining",
    "Wallpaper installation",
    "Wallpaper removal",
    "Epoxy flooring",
    "Concrete coating",
    "Popcorn ceiling removal",
    "Drywall repair",
    "Drywall installation",
    "Plaster repair",
    "Stucco repair",
    "Caulking services"
  ],
  "Pest & Animal Control": [
    "Pest control",
    "Termite control",
    "Bed bug treatment",
    "Mosquito control",
    "Rodent control",
    "Wildlife removal",
    "Bird control",
    "Bee removal",
    "Wasp removal",
    "Ant control",
    "Cockroach control",
    "Flea treatment"
  ],
  "Moving & Junk": [
    "Local moving",
    "Long distance moving",
    "Furniture moving",
    "Junk removal",
    "Furniture removal",
    "Appliance removal",
    "Mattress disposal",
    "Estate cleanout",
    "Foreclosure cleanout",
    "Storage unit cleanout",
    "Donation pickup"
  ],
  "Specialty Home Services": [
    "Handyman",
    "Home inspection",
    "Mold remediation",
    "Water damage restoration",
    "Fire damage restoration",
    "Flood cleanup",
    "Asbestos removal",
    "Lead paint removal",
    "Radon mitigation",
    "Septic tank service",
    "Well pump service",
    "Masonry",
    "Brick repair",
    "Chimney sweep",
    "Fireplace installation",
    "Sauna installation",
    "Hot tub installation",
    "Pool installation",
    "Concrete work",
    "Stamped concrete",
    "Paving"
  ],
  "Auto & Garage": [
    "Mobile mechanic",
    "Mobile car detailing",
    "Mobile oil change",
    "Windshield repair",
    "Dent removal",
    "Tire service",
    "Garage floor coating",
    "Garage organization"
  ],
  "Personal & Pet Services": [
    "Dog walking",
    "Pet sitting",
    "Pet grooming",
    "Mobile pet grooming",
    "Doggy daycare",
    "Senior care at home",
    "Babysitting service",
    "Tutoring at home",
    "Personal chef",
    "Meal prep service"
  ],
  "Tech & Appliance": [
    "Computer repair",
    "Phone repair",
    "TV repair",
    "Smart home setup",
    "WiFi setup",
    "Security system monitoring",
    "Home theater installation",
    "Projector installation"
  ]
};
